CREATE TABLE TEACHERS(
id INT IDENTITY PRIMARY KEY,
NAME VARCHAR(50),
SUBJECT VARCHAR(50)
)

CREATE TABLE STUDENTS(
id INT IDENTITY PRIMARY KEY,
NAME VARCHAR(50),
AGE INT,
COURSE VARCHAR(50),
GRADE VARCHAR(50),
CLASS_TEACHER INT NOT NULL
)

CREATE TABLE MARKS(
id INT IDENTITY PRIMARY KEY,
STUDENT_ID INT NOT NULL,
TAMIL INT,
ENGLISH INT,
MATHS INT,
SCIENCE INT,
SOCIAL_SCIENCE INT
)

CREATE TABLE PROJECT(
id INT IDENTITY PRIMARY KEY,
STUDENT_ID INT NOT NULL,
TITLE VARCHAR(500),
PROJECT_SUBJECT VARCHAR(500),
PROJECT_MARKS INT
)

ALTER TABLE STUDENTS
ADD CONSTRAINT FK_ClassTeacher
FOREIGN KEY (CLASS_TEACHER) REFERENCES TEACHERS(id)

ALTER TABLE MARKS
ADD CONSTRAINT FK_StudentId
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(id)

ALTER TABLE PROJECT
ADD CONSTRAINT FK_Student_Project
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(id)

CREATE TABLE Users(
id INT IDENTITY PRIMARY KEY,
username VARCHAR(500),
password VARCHAR(500)
)

TRUNCATE TABLE TEACHERS
TRUNCATE TABLE STUDENTS
TRUNCATE TABLE MARKS
TRUNCATE TABLE PROJECT
TRUNCATE TABLE Users

DELETE FROM PROJECT DBCC CHECKIDENT('STUDENTDB.DBO.PROJECT',RESEED,0)

ALTER TABLE PROJECT
DROP CONSTRAINT FK_StudentId_ProjectId
