CREATE TABLE STUDENTS(
id INT IDENTITY PRIMARY KEY,
NAME VARCHAR(50),
AGE INT,
COURSE VARCHAR(50),
GRADE VARCHAR(50),
CLASS_TEACHER VARCHAR(50)
)

CREATE TABLE MARKS(
id INT IDENTITY PRIMARY KEY,
TAMIL INT,
ENGLISH INT,
MATHS INT,
SCIENCE INT,
SOCIAL_SCIENCE INT
)

CREATE TABLE TEACHERS(
id INT IDENTITY PRIMARY KEY,
NAME VARCHAR(50),
SUBJECT VARCHAR(50)
)